### ISSUE TITLE
detalles para cambiar

### ISSUE THREAD

**Issue by Nahuele** [SfrRonaldo/codnas-q#1]
- agrandar un poco el dendrogram, se ve muy chico 
- agrandar letra en general
- achicar espacios en costados de tarjetas (para reducir espacios en blanco)
![image](https://user-images.githubusercontent.com/36633523/130511414-4c435d83-c21a-4d96-ad42-142b1e435907.png)

- mostrar lista separada por coma de los pdb que matchean
![image](https://user-images.githubusercontent.com/36633523/130512326-1e5443ee-aa80-4b06-a434-ba9edd66847e.png)

- las comparaciones del cluster CQ3ggu no funcionan (no se si estan) y en la version de heroku de codnas-Q tiene mas conformeros que en la version de ReactJS. De hecho no figura 1rpi que es uno del par maximo.
version ReactJS
![image](https://user-images.githubusercontent.com/36633523/130513298-1e2cadfd-f6b1-4777-9ec4-ab9352a4f281.png)
version heroku:
![image](https://user-images.githubusercontent.com/36633523/130513049-5e13a344-18f8-4294-8ee6-b246f3a4797e.png)

- autocompletar Form de Advanced Search con Query del usuario. Por ej: si usario busca desde el /Home Organismo Escherichia coli, autocompletar el campo Organismo con Escherichia coli en /adv-search.

**Comment by iKurito** [comment]
1. Dendrogram agrandado
2. En proceso
3. Espacios achicados, pero difiere mucho de la resolución de la pantalla
4. En proceso
5. Si funcionan, solo que se muestran 5 por página y no muestra todas en una, solo hay que avanzar en el paginador y se encontrarán los demás
6. Hecho
