### ISSUE TITLE
RegEx para reconocer inputs de busqueda del usuario 

### ISSUE THREAD

**Issue by Nahuele** [SfrRonaldo/codnas-q#4]
Agregar RegEx para detectar lo que el usuario ingresa, esto salvaria el error de que ponga un espacio adelante por ejemplo y no lo encuentre por eso.

[UniProt](https://www.uniprot.org/help/accession_numbers):
[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}

**Comment by iKurito** [comment]
Corregido c:
