### ISSUE TITLE
new problems in adv search?

### ISSUE THREAD

**Issue by Nahuele** [SfrRonaldo/codnas-q#5]
- Buscando Temperaturas de 0 a 20 aparece el cluster CQ3ezf, match en 3ez9, en la web figura que no tiene Temperatura, y en la tabla figura que tiene 100 de Temp.
- Si busco Rigid body AND Organism = AZOARCUS, figura un cluster de Tertiary Deformations (CQ2ewm)
- Si busco  Resolution entre 1 y 1.5, y length entre 50 y 200, aparecen clusters de 3000 de length

**Comment by iKurito** [comment]
Corregido c:
