### ISSUE TITLE
busquedas desde el Home

### ISSUE THREAD

**Issue by Nahuele** [SfrRonaldo/codnas-q#6]
Hay una proteina que tenemos que se llama miraculin, pero si busco miraculin no la encuentra (la palabra completa es Miraculin-Like en uno de los conformeros, y Miraculin en el otro), cluster: 3iir

- El problema es que esa anotacion esta en **descripcion**, y en el _All fields_ del home no me lee descripcion. Por eso no se encuentra. Agregar busqueda en el campo descripcion tambien?
- la busqueda por pdb diferencia entre mayusc y minusculas, ej 2v8g se encuentra perfecto, pero 2V8G no se encuentra, habria que hacerla case unsensitive, quizas con regex? (pedir a Nahue si es necesario)
- la comparacion del ejemplo en la home no funciona http://localhost/cluster/CQ2vcq/pairs/1iyh-1iyi

**Comment by iKurito** [comment]
- Búsqueda en el campo descripción está agregada en el Home.
- Ya se puede encontrar por PDB en minúscula o mayúscula.
- La comparación del ejemplo en la home ya funciona, actualicé el servicio correspondiente.
